name: Build and test L2s

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Load ccache
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildroot-ccache
        key: ${{ runner.os }}-${{ runner.arch }}-ccache

    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt install -qq libelf-dev binutils-powerpc64le-linux-gnu gcc-powerpc64le-linux-gnu bison flex tar make gzip cmake python3 python3-pexpect device-tree-compiler libpixman-1-0 libgio-qt0

    - name: Checkout git submodules
      run: |
        git submodule update --init --depth 10
        ./qemu/scripts/git-submodule.sh update  ui/keycodemapdb tests/fp/berkeley-testfloat-3 tests/fp/berkeley-softfloat-3 dtc roms/SLOF
    - name: Configure
      run: |
        make kvm_l1_defconfig
        ./buildroot/utils/config --file output/.config -e BR2_TOOLCHAIN_EXTERNAL
        make olddefconfig
    - name: Build
      run: make -j $(nproc)
    - name: Pack artifacts
      run: |
         scripts/copy_qemu.sh
         scripts/copy_images.sh
         tar -cvf artifacts.tar overlay/qemu-system-ppc64 overlay/rootfs.cpio overlay/slof.bin overlay/vmlinux output/build/host-qemu-custom/build/qemu-system-ppc64
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
        path: artifacts.tar
        retention-days: 2 # short since it's only to be reused below
  test:
    needs: build
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        api: [
          "v1",
          "v2",
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt install -qq libelf-dev binutils-powerpc64le-linux-gnu gcc-powerpc64le-linux-gnu bison flex tar make gzip cmake python3 python3-pexpect device-tree-compiler libpixman-1-0 libgio-qt0
    - uses: actions/download-artifact@v3
      with:
        name: build-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
    - name: Find
      run: find .
    - name: Unpack artifacts
      run: tar xvf artifacts.tar
    - name: Find
      run: find .
    - name: Test ${{ matrix.api }} API
      run: ./test_L1.sh --${{ matrix.api }}

